<?php

namespace Babesk\Proxies\__CG__\Babesk\ORM;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SystemUsers extends \Babesk\ORM\SystemUsers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'forename', 'username', 'password', 'email', 'telephone', 'birthday', 'last_login', 'login_tries', 'first_passwd', 'locked', 'credit', 'soli', 'religion', 'foreign_language', 'special_course', 'schbasAccounting', 'usersInGradesAndSchoolyears', 'usersInClassesAndCategories', 'cards', 'priceGroup', 'groups', 'bookLending', 'selfpayingBooks');
        }

        return array('__isInitialized__', 'id', 'name', 'forename', 'username', 'password', 'email', 'telephone', 'birthday', 'last_login', 'login_tries', 'first_passwd', 'locked', 'credit', 'soli', 'religion', 'foreign_language', 'special_course', 'schbasAccounting', 'usersInGradesAndSchoolyears', 'usersInClassesAndCategories', 'cards', 'priceGroup', 'groups', 'bookLending', 'selfpayingBooks');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SystemUsers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setForename($forename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForename', array($forename));

        return parent::setForename($forename);
    }

    /**
     * {@inheritDoc}
     */
    public function getForename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForename', array());

        return parent::getForename();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', array($birthday));

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', array());

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin($lastLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($lastLogin));

        return parent::setLastLogin($lastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginTries($loginTries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginTries', array($loginTries));

        return parent::setLoginTries($loginTries);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginTries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginTries', array());

        return parent::getLoginTries();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstPasswd($firstPasswd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstPasswd', array($firstPasswd));

        return parent::setFirstPasswd($firstPasswd);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstPasswd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstPasswd', array());

        return parent::getFirstPasswd();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($locked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', array($locked));

        return parent::setLocked($locked);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocked', array());

        return parent::getLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredit($credit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredit', array($credit));

        return parent::setCredit($credit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredit', array());

        return parent::getCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoli($soli)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoli', array($soli));

        return parent::setSoli($soli);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoli()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoli', array());

        return parent::getSoli();
    }

    /**
     * {@inheritDoc}
     */
    public function setReligion($religion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReligion', array($religion));

        return parent::setReligion($religion);
    }

    /**
     * {@inheritDoc}
     */
    public function getReligion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReligion', array());

        return parent::getReligion();
    }

    /**
     * {@inheritDoc}
     */
    public function setForeignLanguage($foreignLanguage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForeignLanguage', array($foreignLanguage));

        return parent::setForeignLanguage($foreignLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getForeignLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForeignLanguage', array());

        return parent::getForeignLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialCourse($specialCourse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialCourse', array($specialCourse));

        return parent::setSpecialCourse($specialCourse);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialCourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialCourse', array());

        return parent::getSpecialCourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchbasAccounting(\Babesk\ORM\SchbasAccounting $schbasAccounting = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchbasAccounting', array($schbasAccounting));

        return parent::setSchbasAccounting($schbasAccounting);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchbasAccounting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchbasAccounting', array());

        return parent::getSchbasAccounting();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersInGradesAndSchoolyear(\Babesk\ORM\SystemUsersInGradesAndSchoolyears $usersInGradesAndSchoolyears)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersInGradesAndSchoolyear', array($usersInGradesAndSchoolyears));

        return parent::addUsersInGradesAndSchoolyear($usersInGradesAndSchoolyears);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersInGradesAndSchoolyear(\Babesk\ORM\SystemUsersInGradesAndSchoolyears $usersInGradesAndSchoolyears)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersInGradesAndSchoolyear', array($usersInGradesAndSchoolyears));

        return parent::removeUsersInGradesAndSchoolyear($usersInGradesAndSchoolyears);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersInGradesAndSchoolyears()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersInGradesAndSchoolyears', array());

        return parent::getUsersInGradesAndSchoolyears();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersInClassesAndCategory(\Babesk\ORM\UserInClassAndCategory $usersInClassesAndCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersInClassesAndCategory', array($usersInClassesAndCategories));

        return parent::addUsersInClassesAndCategory($usersInClassesAndCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersInClassesAndCategory(\Babesk\ORM\UserInClassAndCategory $usersInClassesAndCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersInClassesAndCategory', array($usersInClassesAndCategories));

        return parent::removeUsersInClassesAndCategory($usersInClassesAndCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersInClassesAndCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersInClassesAndCategories', array());

        return parent::getUsersInClassesAndCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCard(\Babesk\ORM\BabeskCards $cards)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCard', array($cards));

        return parent::addCard($cards);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCard(\Babesk\ORM\BabeskCards $cards)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCard', array($cards));

        return parent::removeCard($cards);
    }

    /**
     * {@inheritDoc}
     */
    public function getCards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCards', array());

        return parent::getCards();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceGroup(\Babesk\ORM\BabeskPriceGroups $priceGroup = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceGroup', array($priceGroup));

        return parent::setPriceGroup($priceGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceGroup', array());

        return parent::getPriceGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\Babesk\ORM\SystemGroups $groups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', array($groups));

        return parent::addGroup($groups);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\Babesk\ORM\SystemGroups $groups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', array($groups));

        return parent::removeGroup($groups);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', array());

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addBookLending(\Babesk\ORM\SchbasInventory $bookLending)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBookLending', array($bookLending));

        return parent::addBookLending($bookLending);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBookLending(\Babesk\ORM\SchbasInventory $bookLending)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBookLending', array($bookLending));

        return parent::removeBookLending($bookLending);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookLending()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookLending', array());

        return parent::getBookLending();
    }

    /**
     * {@inheritDoc}
     */
    public function addSelfpayingBook(\Babesk\ORM\SchbasBooks $selfpayingBooks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSelfpayingBook', array($selfpayingBooks));

        return parent::addSelfpayingBook($selfpayingBooks);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSelfpayingBook(\Babesk\ORM\SchbasBooks $selfpayingBooks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSelfpayingBook', array($selfpayingBooks));

        return parent::removeSelfpayingBook($selfpayingBooks);
    }

    /**
     * {@inheritDoc}
     */
    public function getSelfpayingBooks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelfpayingBooks', array());

        return parent::getSelfpayingBooks();
    }

}
