<?php

/**
 * This file is used for gettext-Editors that fetch the elements automatically
 * from the Sourcecode. Since the Modulepaths are created from a database the
 * editors delete the translations every time they autoupdate.
 * This file prevents it
 */

die('NoAccess');

_g("modulepath_root/publicData");
_g("modulepath_root/publicData/JsDataProcessor");
_g("modulepath_root/publicData/JsDataProcessor/InputdataCheck");
_g("modulepath_root/publicData/GeneralPublicData");
_g("modulepath_root/publicData/GeneralPublicData/LoginHelp");
_g("modulepath_root/publicData/Babesk");
_g("modulepath_root/publicData/Babesk/Menu");
_g("modulepath_root/web");
_g("modulepath_root/web/Settings");
_g("modulepath_root/web/Settings/SettingsChangePassword");
_g("modulepath_root/web/Settings/SettingsMainMenu");
_g("modulepath_root/web/Settings/ChangeEmail");
_g("modulepath_root/web/Settings/ChangePresetPassword");
_g("modulepath_root/web/Schbas");
_g("modulepath_root/web/Schbas/LoanSystem");
_g("modulepath_root/web/Messages");
_g("modulepath_root/web/Messages/MessageMainMenu");
_g("modulepath_root/web/Messages/MessageAdmin");
_g("modulepath_root/web/PVau");
_g("modulepath_root/web/PVau/Pvp");
_g("modulepath_root/web/Kuwasys");
_g("modulepath_root/web/Kuwasys/ClassList");
_g("modulepath_root/web/Kuwasys/MainMenu");
_g("modulepath_root/web/Kuwasys/ClassDetails");
_g("modulepath_root/web/Fits");
_g("modulepath_root/web/Fits/Zeugnis");
_g("modulepath_root/web/Fits/Quiz");
_g("modulepath_root/web/Fits/Fmenu");
_g("modulepath_root/web/Babesk");
_g("modulepath_root/web/Babesk/Order");
_g("modulepath_root/web/Babesk/Menu");
_g("modulepath_root/web/Babesk/Help");
_g("modulepath_root/web/Babesk/ChangePassword");
_g("modulepath_root/web/Babesk/Cancel");
_g("modulepath_root/web/Babesk/Account");
_g("modulepath_root/administrator");
_g("modulepath_root/administrator/Gnissel");
_g("modulepath_root/administrator/Gnissel/GDelUser");
_g("modulepath_root/administrator/Gnissel/GChangeCard");
_g("modulepath_root/administrator/Gnissel/GUnlockUser");
_g("modulepath_root/administrator/Gnissel/GChangePassword");
_g("modulepath_root/administrator/Gnissel/GCardInfo");
_g("modulepath_root/administrator/Statistics");
_g("modulepath_root/administrator/Statistics/KuwasysStats");
_g("modulepath_root/administrator/Statistics/MessageStats");
_g("modulepath_root/administrator/Kuwasys");
_g("modulepath_root/administrator/Kuwasys/Classteachers");
_g("modulepath_root/administrator/Kuwasys/Classes");
_g("modulepath_root/administrator/Kuwasys/KuwasysUsers");
_g("modulepath_root/administrator/Schbas");
_g("modulepath_root/administrator/Schbas/SchbasMessages");
_g("modulepath_root/administrator/Schbas/SchbasAccounting");
_g("modulepath_root/administrator/Schbas/SchbasSettings");
_g("modulepath_root/administrator/Schbas/BookInfo");
_g("modulepath_root/administrator/Schbas/Retour");
_g("modulepath_root/administrator/Schbas/Loan");
_g("modulepath_root/administrator/Schbas/Inventory");
_g("modulepath_root/administrator/Schbas/Booklist");
_g("modulepath_root/administrator/Messages");
_g("modulepath_root/administrator/Messages/MessageAdmin");
_g("modulepath_root/administrator/Messages/MessageTemplate");
_g("modulepath_root/administrator/Messages/MessageAuthor");
_g("modulepath_root/administrator/Fits");
_g("modulepath_root/administrator/Fits/FitsSettins");
_g("modulepath_root/administrator/Fits/FitsCheck");
_g("modulepath_root/administrator/Babesk");
_g("modulepath_root/administrator/Babesk/Soli");
_g("modulepath_root/administrator/Babesk/Recharge");
_g("modulepath_root/administrator/Babesk/Priceclass");
_g("modulepath_root/administrator/Babesk/Menu");
_g("modulepath_root/administrator/Babesk/Meals");
_g("modulepath_root/administrator/Babesk/Checkout");
_g("modulepath_root/administrator/System");
_g("modulepath_root/administrator/System/Schooltype");
_g("modulepath_root/administrator/System/CardChange");
_g("modulepath_root/administrator/System/WebHomepageSettings");
_g("modulepath_root/administrator/System/PresetPassword");
_g("modulepath_root/administrator/System/EmailConfiguration");
_g("modulepath_root/administrator/System/CardInfo");
_g("modulepath_root/administrator/System/Logs");
_g("modulepath_root/administrator/System/Groups");
_g("modulepath_root/administrator/System/Admin");
_g("modulepath_root/administrator/System/Help");
_g("modulepath_root/administrator/System/SpecialCourse");
_g("modulepath_root/administrator/System/ForeignLanguage");
_g("modulepath_root/administrator/System/Religion");
_g("modulepath_root/administrator/System/User");
_g("modulepath_root/administrator/System/Grade");
_g("root/administrator/Babesk/Checkout");
_g("modulepath_root/administrator/Babesk/BabeskTimeSettings");
_g("modulepath_root/administrator/Fits/FitsSettings");
_g("modulepath_root/administrator/System/GroupSettings");
_g("modulepath_root/administrator/System/ModuleSettings");
_g("modulepath_root/administrator/System/Schoolyear");

?>
