// Generated by Coffeescript
var Col, DashboardBox, InventoryPanel, Panel, PreparationPanel, React, Row, StatisticsRow;

React = require('react');

Row = require('react-bootstrap/lib/Row');

Col = require('react-bootstrap/lib/Col');

Panel = require('react-bootstrap/lib/Panel');

PreparationPanel = require('./lib/Preparation/PreparationPanel.js');

InventoryPanel = require('./lib/Inventory/InventoryPanel');

StatisticsRow = require('./lib/Statistics/StatisticsRow');

DashboardBox = React.createClass({
  render: function() {
    return React.createElement("div", null, React.createElement(StatisticsRow, null), React.createElement(Row, null, React.createElement(Col, {
      "sm": 12.
    }, React.createElement(Panel, {
      "className": 'panel-dashboard',
      "header": React.createElement("h4", null, "Schbas")
    }, "Kommt vielleicht sp\u00e4ter :)")), React.createElement(Col, {
      "sm": 12.,
      "lg": 6.
    }, React.createElement(Panel, {
      "className": 'panel-dashboard',
      "header": React.createElement("h4", null, "B\u00fccher")
    }, "Kommt vielleicht sp\u00e4ter :)")), React.createElement(Col, {
      "sm": 12.,
      "lg": 6.
    }, React.createElement(Panel, {
      "className": 'panel-dashboard',
      "header": React.createElement("h4", null, "Exemplare")
    }, React.createElement(InventoryPanel, null))), React.createElement(Col, {
      "sm": 12.
    }, React.createElement(Panel, {
      "className": 'panel-dashboard',
      "header": React.createElement("h4", null, "Vorbereitungen")
    }, React.createElement(PreparationPanel, null)))));
  }
});

React.render(React.createElement(DashboardBox, null), $('#react')[0]);
