// Generated by Coffeescript
var PreparationPanel, React, renderPrepararationPanel;

React = require('react');

PreparationPanel = require('./lib/Preparation/PreparationPanel.js');

renderPrepararationPanel = function() {
  return React.render(React.createElement(PreparationPanel, null), $('#preparation-panel > div.panel-body')[0]);
};

renderPrepararationPanel();
