// Generated by Coffeescript
var InventoryPanel, PreparationPanel, React, renderInventoryPanel, renderPreparationPanel;

React = require('react');

PreparationPanel = require('./lib/Preparation/PreparationPanel.js');

InventoryPanel = require('./lib/Inventory/InventoryPanel');

renderInventoryPanel = function() {
  return React.render(React.createElement(InventoryPanel, null), $('#inventory-panel > div.panel-body')[0]);
};

renderPreparationPanel = function() {
  return React.render(React.createElement(PreparationPanel, null), $('#preparation-panel > div.panel-body')[0]);
};

renderInventoryPanel();

renderPreparationPanel();
