// Generated by Coffeescript
var App, Button, Col, Icon, Panel, React, Row;

React = require('react');

Button = require('react-bootstrap/lib/Button');

Icon = require('lib/FontAwesomeIcon');

Panel = require('react-bootstrap/lib/Panel');

Row = require('react-bootstrap/lib/Row');

Col = require('react-bootstrap/lib/Col');

App = React.createClass({
  getInitialState: function() {
    return {};
  },
  render: function() {
    return React.createElement("div", null, React.createElement(Row, null, React.createElement("div", {
      "className": 'user-header'
    }, React.createElement("h3", null, "Benutzer \"Pascal Ernst\""), React.createElement(Row, {
      "className": 'tabs'
    }, React.createElement("a", {
      "href": '#',
      "className": "text-center"
    }, React.createElement(Icon, {
      "name": "eye",
      "size": "large"
    }), "\u00dcbersicht"), React.createElement("a", {
      "href": '#'
    }, React.createElement(Icon, {
      "name": "bar-chart",
      "size": "large"
    }), "Statistiken"), React.createElement("a", {
      "href": '#'
    }, React.createElement(Icon, {
      "name": "cog",
      "size": "large"
    }), "Einstellungen")))), React.createElement(Row, null));
  }
});

React.render(React.createElement(App, null), $('#entry')[0]);
