// Generated by Coffeescript
var Button, CheckboxButton, React, classnames;

React = require('react');

React.Bootstrap = require('react-bootstrap');

Button = React.Bootstrap.Button;

classnames = require('classnames');

CheckboxButton = React.createClass({
  getInitialState: function() {
    return {
      isChecked: false
    };
  },
  getDefaultProps: function() {
    return {
      offText: '',
      onText: '',
      offStyle: 'default',
      onStyle: 'primary',
      onClick: function() {
        return true;
      }
    };
  },
  onClick: function() {
    if (this.props.onClick()) {
      return this.setState({
        isChecked: !this.state.isChecked
      });
    }
  },
  render: function() {
    var bsStyle, iconClasses;
    bsStyle = this.state.isChecked ? this.props.onStyle : this.props.offStyle;
    iconClasses = classnames({
      'fa fa-fw': true,
      'fa-square-o': !this.state.isChecked,
      'fa-check-square-o': this.state.isChecked
    });
    return React.createElement(Button, {
      "bsStyle": bsStyle,
      "onClick": this.onClick
    }, React.createElement("i", {
      "className": iconClasses
    }), "\u00a0", (this.state.isChecked ? this.props.onText : this.props.offText), this.props.children);
  }
});

module.exports = CheckboxButton;
