// Generated by Coffeescript
var LoadingIcon, React;

React = require('react');

LoadingIcon = React.createClass({
  render: function() {
    return React.createElement("i", {
      "className": 'fa fa-spin fa-cog'
    });
  }
});

exports.LoadingIcon = LoadingIcon;
