// Generated by Coffeescript
var React, StatusIcon, classnames;

React = require('react');

classnames = require('classnames');

StatusIcon = React.createClass({
  render: function() {
    var classes;
    classes = classnames({
      'fa fa-3x fa-fw pull-left': true,
      'fa-times-circle': this.props.status === 'danger',
      'fa-exclamation-circle': this.props.status === 'warning',
      'fa-info-circle': this.props.status === 'info',
      'fa-check-circle': this.props.status === 'success'
    });
    return React.createElement("i", {
      "className": classes
    });
  }
});

exports.StatusIcon = StatusIcon;
