// Generated by Coffeescript
var Button, Icon, Input, React, classnames;

React = require('react');

Button = require('react-bootstrap/lib/Button');

Input = require('react-bootstrap/lib/Input');

Icon = require('lib/FontAwesomeIcon');

classnames = require('classnames');

module.exports = React.createClass({
  getInitialState: function() {
    return {
      newBarcodeValue: ''
    };
  },
  getDefaultProps: function() {
    return {
      barcodes: [],
      onNewBarcode: function() {
        return {};
      },
      onNewBarcodeRemove: function(barcodeIndex) {
        return console.log(barcodeIndex);
      }
    };
  },
  handleNewBarcode: function() {
    this.props.onNewBarcode(this.state.newBarcodeValue);
    return this.setState({
      newBarcodeValue: ''
    });
  },
  handleNewBarcodeKeyPress: function(event) {
    if (event.which === 13) {
      return this.handleNewBarcode();
    }
  },
  handleNewBarcodeValueChange: function(event) {
    return this.setState({
      newBarcodeValue: event.target.value
    });
  },
  deleteButton: function(barcodeIndex) {
    return React.createElement(Button, {
      "bsStyle": 'danger',
      "onClick": this.props.onNewBarcodeRemove.bind(null, barcodeIndex)
    }, React.createElement(Icon, {
      "name": 'trash-o',
      "fixedWidth": true
    }));
  },
  render: function() {
    var addButton;
    addButton = React.createElement(Button, {
      "bsStyle": 'success',
      "onClick": this.handleNewBarcode
    }, React.createElement(Icon, {
      "name": 'plus-square-o',
      "fixedWidth": true
    }));
    return React.createElement("div", null, this.props.barcodes.map((function(_this) {
      return function(barcode, index) {
        return React.createElement(Input, {
          "type": 'text',
          "key": index,
          "value": barcode,
          "readOnly": true,
          "buttonAfter": _this.deleteButton(index)
        });
      };
    })(this)), React.createElement(Input, {
      "type": 'text',
      "value": this.state.newBarcodeValue,
      "buttonAfter": addButton,
      "onKeyPress": this.handleNewBarcodeKeyPress,
      "onChange": this.handleNewBarcodeValueChange
    }));
  }
});
