// Generated by Coffeescript
var AddInventoryBox, Button, ButtonGroup, Icon, React;

React = require('react');

Button = require('react-bootstrap/lib/Button');

Icon = require('lib/FontAwesomeIcon');

ButtonGroup = require('react-bootstrap/lib/ButtonGroup');

AddInventoryBox = require('./AddInventoryBox');

module.exports = React.createClass({
  getInitialState: function() {
    return {
      showAddInventory: false,
      newBarcodes: []
    };
  },
  handleAddInventoryClicked: function() {
    return this.setState({
      showAddInventory: true
    });
  },
  handleSubmitAddInventoryClicked: function() {
    toastr.error('Kommt noch!');
    return this.setState({
      newBarcodes: []
    });
  },
  handleCancelAddInventoryClicked: function() {
    return this.setState({
      showAddInventory: false
    });
  },
  handleNewBarcode: function(barcode) {
    var barcodes;
    barcodes = this.state.newBarcodes;
    barcodes.push(barcode);
    return this.setState({
      newBarcodes: barcodes
    });
  },
  handleNewBarcodeRemove: function(barcodeIndex) {
    var barcodes;
    barcodes = this.state.newBarcodes;
    barcodes.splice(barcodeIndex, 1);
    return this.setState({
      newBarcodes: barcodes
    });
  },
  render: function() {
    return React.createElement("div", null, (this.state.showAddInventory ? React.createElement(ButtonGroup, {
      "justified": true
    }, React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'default',
      "onClick": this.handleCancelAddInventoryClicked
    }, React.createElement(Icon, {
      "name": 'trash-o'
    }), " Hinzuf\u00fcgen abbrechen")), React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'primary',
      "disabled": this.state.newBarcodes.length === 0,
      "onClick": this.handleSubmitAddInventoryClicked
    }, React.createElement(Icon, {
      "name": 'upload'
    }), " Hinzuf\u00fcgen"))) : React.createElement(ButtonGroup, {
      "justified": true
    }, React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'default',
      "onClick": this.handleAddInventoryClicked
    }, "Exemplare hinzuf\u00fcgen")))), React.createElement("hr", null), (this.state.showAddInventory ? React.createElement(AddInventoryBox, {
      "barcodes": this.state.newBarcodes,
      "onNewBarcode": this.handleNewBarcode,
      "onNewBarcodeRemove": this.handleNewBarcodeRemove
    }) : void 0));
  }
});
