// Generated by Coffeescript
var AddInventoryBox, Button, ButtonGroup, DeleteInventoryBox, Icon, React, SolveDuplicatesBox;

React = require('react');

Button = require('react-bootstrap/lib/Button');

Icon = require('lib/FontAwesomeIcon');

ButtonGroup = require('react-bootstrap/lib/ButtonGroup');

AddInventoryBox = require('./AddInventoryBox');

DeleteInventoryBox = require('./DeleteInventoryBox');

SolveDuplicatesBox = require('./SolveDuplicatesBox');

module.exports = React.createClass({
  getInitialState: function() {
    return {
      showAddInventory: false,
      showEditDuplicates: false,
      showDeleteInventory: false,
      newBarcodes: [],
      deleteBarcodes: [],
      askDuplicatesData: {}
    };
  },
  handleAddInventoryClicked: function() {
    return this.setState({
      showAddInventory: true
    });
  },
  handleSubmitAddInventoryClicked: function() {
    return $.getJSON('index.php?module=administrator|Schbas|Inventory', {
      getBooksForBarcodes: true,
      barcodes: this.state.newBarcodes
    }).done((function(_this) {
      return function(barcodes) {
        if (barcodes.duplicated.length > 0) {
          barcodes.duplicated = barcodes.duplicated.map(function(barcodeGroup) {
            barcodeGroup.assignedBookId = false;
            return barcodeGroup;
          });
          return _this.setState({
            askDuplicatesData: barcodes,
            showEditDuplicates: true
          });
        } else {
          return _this.uploadBarcodes(barcodes.unique);
        }
      };
    })(this)).fail(function(jqxhr) {
      return toastr.error(jqxhr.responseText, 'Fehler');
    });
  },
  handleSubmitAddDuplicatedInventoryClicked: function() {
    var barcodesToUpload;
    barcodesToUpload = this.state.askDuplicatesData.unique;
    this.state.askDuplicatesData.duplicated.forEach(function(group) {
      return group.barcodes.forEach(function(barcode) {
        return barcodesToUpload.push({
          barcode: barcode,
          bookId: group.assignedBookId
        });
      });
    });
    return this.uploadBarcodes(barcodesToUpload);
  },
  uploadBarcodes: function(barcodes) {
    return $.post('index.php?module=administrator|Schbas|Inventory|Add', {
      barcodesWithBookIds: barcodes
    }).done((function(_this) {
      return function(res) {
        toastr.success(res, 'Erfolgreich');
        return _this.setState({
          newBarcodes: [],
          showAddInventory: false
        });
      };
    })(this)).fail(function(jqxhr) {
      return toastr.error(jqxhr.responseText, 'Ein Fehler ist aufgetreten');
    });
  },
  handleCancelAddInventoryClicked: function() {
    return this.setState({
      showAddInventory: false
    });
  },
  handleNewBarcode: function(barcode) {
    var barcodes;
    barcodes = this.state.newBarcodes;
    barcodes.push(barcode);
    return this.setState({
      newBarcodes: barcodes
    });
  },
  handleNewBarcodeRemove: function(barcodeIndex) {
    var barcodes;
    barcodes = this.state.newBarcodes;
    barcodes.splice(barcodeIndex, 1);
    return this.setState({
      newBarcodes: barcodes
    });
  },
  handleDuplicateSelectedBookChange: function(groupKey, bookId) {
    var askDuplicatesDataTmp;
    askDuplicatesDataTmp = this.state.askDuplicatesData;
    askDuplicatesDataTmp['duplicated'][groupKey]['assignedBookId'] = bookId;
    return this.setState({
      askDuplicatesData: askDuplicatesDataTmp
    });
  },
  handleDeleteInventoryClicked: function() {
    return this.setState({
      showDeleteInventory: true
    });
  },
  handleCancelDeleteInventoryClicked: function() {
    return this.setState({
      showDeleteInventory: false
    });
  },
  handleSubmitDeleteInventoryClicked: function() {
    return bootbox.confirm('Wollen sie die Exemplare wirklich löschen?', (function(_this) {
      return function(res) {
        if (res) {
          return $.post('index.php?module=administrator|Schbas|Inventory|Delete', {
            barcodes: _this.state.deleteBarcodes
          }).done(function(res) {
            toastr.success(res, 'Erfolgreich gelöscht');
            return _this.setState({
              deleteBarcodes: []
            });
          }).fail(function(jqxhr) {
            return toastr.error(jqxhr.responseText, 'Fehler beim Löschen');
          });
        }
      };
    })(this));
  },
  handleDeleteBarcode: function(barcode) {
    var barcodes;
    barcodes = this.state.deleteBarcodes;
    barcodes.push(barcode);
    return this.setState({
      deleteBarcodes: barcodes
    });
  },
  handleDeleteBarcodeRemove: function(barcodeIndex) {
    var barcodes;
    barcodes = this.state.deleteBarcodes;
    barcodes.splice(barcodeIndex, 1);
    return this.setState({
      deleteBarcodes: barcodes
    });
  },
  render: function() {
    return React.createElement("div", null, (this.state.showAddInventory ? React.createElement(ButtonGroup, {
      "justified": true
    }, React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'default',
      "onClick": this.handleCancelAddInventoryClicked
    }, React.createElement(Icon, {
      "name": 'times'
    }), " Hinzuf\u00fcgen abbrechen")), (this.state.showEditDuplicates ? React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'primary',
      "disabled": !this.state.askDuplicatesData.duplicated.every(function(group) {
        return group.assignedBookId !== false;
      }),
      "onClick": this.handleSubmitAddDuplicatedInventoryClicked
    }, React.createElement(Icon, {
      "name": 'upload'
    }), " Hinzuf\u00fcgen")) : React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'primary',
      "disabled": this.state.newBarcodes.length === 0,
      "onClick": this.handleSubmitAddInventoryClicked
    }, React.createElement(Icon, {
      "name": 'upload'
    }), " Hinzuf\u00fcgen")))) : this.state.showDeleteInventory ? React.createElement(ButtonGroup, {
      "justified": true
    }, React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'default',
      "onClick": this.handleCancelDeleteInventoryClicked
    }, React.createElement(Icon, {
      "name": 'times'
    }), " L\u00f6schen abbrechen")), React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'danger',
      "disabled": this.state.deleteBarcodes.length === 0,
      "onClick": this.handleSubmitDeleteInventoryClicked
    }, React.createElement(Icon, {
      "name": 'trash-o'
    }), " L\u00f6schen"))) : React.createElement(ButtonGroup, {
      "justified": true
    }, React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'default',
      "onClick": this.handleAddInventoryClicked
    }, "Exemplare hinzuf\u00fcgen")), React.createElement(ButtonGroup, null, React.createElement(Button, {
      "bsStyle": 'default',
      "onClick": this.handleDeleteInventoryClicked
    }, "Exemplare l\u00f6schen")))), React.createElement("hr", null), (this.state.showAddInventory && this.state.showEditDuplicates ? React.createElement(SolveDuplicatesBox, {
      "uniqueBarcodes": this.state.askDuplicatesData.unique,
      "onSelectedBookChange": this.handleDuplicateSelectedBookChange,
      "barcodeGroups": this.state.askDuplicatesData.duplicated
    }) : this.state.showAddInventory ? React.createElement(AddInventoryBox, {
      "barcodes": this.state.newBarcodes,
      "onNewBarcode": this.handleNewBarcode,
      "onNewBarcodeRemove": this.handleNewBarcodeRemove
    }) : this.state.showDeleteInventory ? React.createElement(DeleteInventoryBox, {
      "barcodes": this.state.deleteBarcodes,
      "onDeleteBarcode": this.handleDeleteBarcode,
      "onDeleteBarcodeRemove": this.handleDeleteBarcodeRemove
    }) : void 0));
  }
});
