// Generated by Coffeescript
var Button, React, classnames;

React = require('react');

Button = require('react-bootstrap/lib/Button');

classnames = require('classnames');

module.exports = React.createClass({
  getDefaultProps: function() {
    return {
      toggled: false,
      onClick: function() {
        return {};
      }
    };
  },
  render: function() {
    var style;
    style = classnames({
      "default": !this.props.toggled,
      danger: this.props.toggled
    });
    return React.createElement(Button, {
      "bsStyle": style,
      "onClick": this.props.onClick
    }, (!this.props.toggled ? 'Exemplare hinzufügen' : 'Hinzufügen abbrechen'));
  }
});
