// Generated by Coffeescript
var BooksToUsersAssignments, React, renderBooksToUsersAssignments;

React = require('react');

BooksToUsersAssignments = require('./lib/BooksToUsersAssignments');

renderBooksToUsersAssignments = function() {
  return React.render(React.createElement(BooksToUsersAssignments, null), $('#view-panel > div.panel-body')[0]);
};

renderBooksToUsersAssignments();
