Babesk\ORM\SystemGlobalSettings:
    type: entity
    table: SystemGlobalSettings
    id:
        id:
            type: integer
            scale: 0
            length: null
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: null
            precision: 0
        value:
            type: string
            scale: 0
            length: null
            precision: 0
    lifecycleCallbacks: {  }
