// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  $("#allowRegistration").bootstrapSwitch();
  return $("#category-select").multiselect({
    selectAllText: "Alle auswählen",
    buttonContainer: '<div class="btn-group" />',
    checkboxName: 'categories[]'
  });
});
