// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  var $btns, $table;
  $table = $('table#selection-table');
  $btns = $table.find('tbody > tr > td.category-row label.meeting-status-button');
  $table.find('tbody > tr > td.category-row input').hide();
  return $btns.on('click', function(event) {
    var $this;
    $btns.filter('.btn-primary').each(function() {
      $(this).toggleClass('btn-primary');
      $(this).toggleClass('btn-success');
      return $(this).find('span.status-text').text('Frei');
    });
    $this = $(this);
    $this.removeClass('btn-success');
    $this.addClass('btn-primary');
    $this.find('span.status-text').text('Anmelden');
    $this.find('input.meetings').prop('checked', true);
    return false;
  });
});
