// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  var $table, disableAllToggles, toggleButtonAppearance;
  $table = $('table#selection-table');
  $table.find('tbody > tr > td.category-row input').hide();
  $('form#selection-form input#selection-submit').on('click', function(event) {
    event.preventDefault();
    if (!$('form#selection-form input.meetings:checked').length) {
      bootbox.alert('Bitte wählen sie eine Anmeldung aus, um sie bestätigen zu können');
      return;
    }
    return bootbox.confirm('Die Anmeldung ist bindend und kann nicht verändert werden. Sind sie sich sicher?', function(res) {
      if (res) {
        return $('form#selection-form').submit();
      }
    });
  });
  $('form#selection-form div.btn-toggle').on('click', function() {
    var $div, $toggle;
    $div = $(this);
    $toggle = $div.find('input.meetings');
    if (!$toggle.prop('checked')) {
      disableAllToggles();
    }
    toggleButtonAppearance($div);
    $toggle.prop('checked', !$toggle.prop('checked'));
    return false;
  });
  toggleButtonAppearance = function($btnGroupDiv) {
    if ($btnGroupDiv.find('label.btn-primary').length) {
      $btnGroupDiv.find('label.btn').toggleClass('btn-primary');
    }
    if ($btnGroupDiv.find('label.btn-danger').length) {
      $btnGroupDiv.find('label.btn').toggleClass('btn-danger');
    }
    if ($btnGroupDiv.find('label.btn-success').length) {
      $btnGroupDiv.find('label.btn').toggleClass('btn-success');
    }
    if ($btnGroupDiv.find('label.btn-info').length) {
      $btnGroupDiv.find('label.btn').toggleClass('btn-info');
    }
    return $btnGroupDiv.find('label.btn').toggleClass('btn-default');
  };
  return disableAllToggles = function() {
    var $alreadyToggled;
    $alreadyToggled = $('form#selection-form div.btn-toggle input.meetings:checked').closest('div.btn-toggle');
    toggleButtonAppearance($alreadyToggled);
    return $alreadyToggled.find('input.meetings').prop('checked', false);
  };
});
