// Generated by Coffeescript
var ChartJs, Col, DoughnutChart, DoughnutStatsChart, NProgress, Panel, Please, React, Row;

React = require('react');

Please = require('pleasejs');

Panel = require('react-bootstrap/lib/Panel');

Row = require('react-bootstrap/lib/Row');

Col = require('react-bootstrap/lib/Col');

ChartJs = require('chart.js');

DoughnutChart = require('react-chartjs').Doughnut;

NProgress = require('nprogress');

ChartJs.defaults.global.responsive = true;

module.exports = React.createClass({
  getInitialState: function() {
    return {
      gradelevelLendStatistics: [],
      subjectLendStatistics: []
    };
  },
  componentDidMount: function() {
    NProgress.start();
    return $.getJSON('index.php?module=administrator|Schbas|Dashboard|Statistics').done((function(_this) {
      return function(res) {
        console.log(res);
        _this.setState(res);
        return NProgress.done();
      };
    })(this)).fail(function(jqxhr) {
      toastr.error(jqxhr.responseText, 'Fehler');
      return NProgress.done();
    });
  },
  render: function() {
    return React.createElement(Row, null, React.createElement(Col, {
      "smOffset": 4.,
      "sm": 4.,
      "mdOffset": 3.,
      "md": 3.
    }, React.createElement(Panel, {
      "className": 'panel-chart',
      "header": 'Ausleihen pro Jahrgang'
    }, React.createElement("div", null, React.createElement(DoughnutStatsChart, {
      "values": this.state.gradelevelLendStatistics
    })))), React.createElement(Col, {
      "sm": 4.,
      "md": 3.
    }, React.createElement(Panel, {
      "className": 'panel-chart',
      "header": 'Ausleihen pro Fach'
    }, React.createElement("div", null, React.createElement(DoughnutStatsChart, {
      "values": this.state.subjectLendStatistics
    })))));
  }
});

DoughnutStatsChart = React.createClass({
  getDefaultProps: function() {
    return {
      values: [],
      header: ''
    };
  },
  render: function() {
    return React.createElement("div", null, (this.props.values.length ? (this.props.values.map(function(el) {
      el.color = Please.make_color({
        saturation: 0.7
      });
      return el;
    }), React.createElement(DoughnutChart, {
      "data": this.props.values
    })) : React.createElement("p", null, "---")));
  }
});
