// Generated by Coffeescript
var AssignmentBox, React, renderAssignmentBox;

React = require('react');

React.Bootstrap = require('react-bootstrap');

AssignmentBox = require('./lib/AssignmentBox.js').AssignmentBox;

renderAssignmentBox = function(overviewData) {
  return React.render(React.createElement(AssignmentBox, {
    "data": overviewData
  }), $('#entry')[0]);
};

$.ajax({
  type: 'GET',
  url: 'index.php?module=administrator|Schbas|BookAssignments|Generate',
  data: 'overview-infos',
  dataType: 'json',
  success: function(data, statusText, jqXHR) {
    console.log(data);
    if ((data.value != null) && data.value === 'error') {
      toastr.error('Konnte die Daten nicht abrufen');
      return;
    }
    return renderAssignmentBox(data);
  },
  error: function(jqXHR, statusText, errorThrown) {
    console.log(jqXHR);
    return toastr.error('Konnte die Daten nicht abrufen');
  }
});
