// Generated by Coffeescript
var AssignmentController, DropdownButton, MenuItem, React;

React = require('react');

React.Bootstrap = require('react-bootstrap');

DropdownButton = React.Bootstrap.DropdownButton;

MenuItem = React.Bootstrap.MenuItem;

AssignmentController = React.createClass({
  render: function() {
    var style, title;
    if (this.props.prepSchoolyear.entriesExist) {
      style = 'info';
      title = 'Zuweisungen existieren';
    } else {
      style = 'danger';
      title = 'Noch keine Zuweisungen';
    }
    return React.createElement(DropdownButton, {
      "bsStyle": style,
      "title": title,
      "pullRight": true
    }, React.createElement(MenuItem, {
      "eventKey": 'edit',
      "key": 'edit',
      "onClick": this.props.handleEdit
    }, "Buchzuweisungen bearbeiten"), React.createElement(MenuItem, {
      "divider": true
    }), React.createElement(MenuItem, {
      "eventKey": 'generate',
      "key": 'generate',
      "onClick": this.props.handleGenerate
    }, "Buchzuweisungen automatisch generieren"), (this.props.prepSchoolyear.entriesExist ? React.createElement(MenuItem, {
      "eventKey": 'delete',
      "key": 'delete',
      "onClick": this.props.handleDelete
    }, "Buchzuweisungen l\u00f6schen") : void 0));
  }
});

module.exports = AssignmentController;
