// Generated by Coffeescript
var Col, DateTimePicker, Deadlines, Input, React, Row, moment;

React = require('react');

React.Bootstrap = require('react-bootstrap');

Input = React.Bootstrap.Input;

Col = React.Bootstrap.Col;

Row = React.Bootstrap.Row;

moment = require('moment');

DateTimePicker = require('react-widgets/lib/DateTimePicker');

Deadlines = React.createClass({
  handleTransferDeadlineChange: function(date) {
    return this.props.onChange(date.toISOString().substr(0, 10), 'schbasDeadlineTransfer');
  },
  handleClaimDeadlineChange: function(date) {
    return this.props.onChange(date.toISOString().substr(0, 10), 'schbasDeadlineClaim');
  },
  render: function() {
    return React.createElement("div", {
      "className": 'form-horizontal'
    }, React.createElement(Row, null, React.createElement(Col, {
      "lg": 6.
    }, React.createElement(Input, {
      "label": 'Geldtransfer',
      "labelClassName": 'col-md-3',
      "wrapperClassName": 'col-md-9'
    }, React.createElement(DateTimePicker, {
      "format": 'dd.MM.yyyy',
      "value": new Date(this.props.deadlines.schbasDeadlineTransfer),
      "time": false,
      "onChange": this.handleTransferDeadlineChange
    }))), React.createElement(Col, {
      "lg": 6.
    }, React.createElement(Input, {
      "label": 'Formularrückgabe',
      "labelClassName": 'col-md-3',
      "wrapperClassName": 'col-md-9'
    }, React.createElement(DateTimePicker, {
      "format": 'dd.MM.yyyy',
      "value": new Date(this.props.deadlines.schbasDeadlineClaim),
      "time": false,
      "onChange": this.handleClaimDeadlineChange
    })))));
  }
});

module.exports = Deadlines;
