// Generated by Coffeescript
var Deadlines, Input, React, moment;

React = require('react');

React.Bootstrap = require('react-bootstrap');

Input = React.Bootstrap.Input;

moment = require('moment');

Deadlines = React.createClass({
  render: function() {
    return React.createElement(Input, {
      "type": 'text',
      "label": 'Deadlines',
      "placeholder": 'Kommt bald...'
    });
  }
});

module.exports = Deadlines;
