// Generated by Coffeescript
var AssignmentController, ButtonGroup, ButtonToolbar, Col, Grid, PrepSchoolyear, PreparationPanel, React, Row, SchbasClaimStatus;

React = require('react');

React.Bootstrap = require('react-bootstrap');

Grid = React.Bootstrap.Grid;

Row = React.Bootstrap.Row;

Col = React.Bootstrap.Col;

ButtonGroup = React.Bootstrap.ButtonGroup;

ButtonToolbar = React.Bootstrap.ButtonToolbar;

PrepSchoolyear = require('./PrepSchoolyear');

AssignmentController = require('./AssignmentController');

SchbasClaimStatus = require('./SchbasClaimStatus');

PreparationPanel = React.createClass({
  getInitialState: function() {
    return {
      prepSchoolyear: {
        active: {
          id: 7,
          name: "14/15",
          entriesExist: true
        },
        alternatives: [
          {
            id: 4,
            name: "15/16",
            entriesExist: false
          }, {
            id: 5,
            name: "12/13",
            entriesExist: true
          }, {
            id: 6,
            name: "13/14",
            entriesExist: true
          }
        ]
      }
    };
  },
  handleSchoolyearChange: function(schoolyearId) {
    toastr.error('Wechseln des Schuljahres ist noch nicht implementiert');
    return console.log(schoolyearId);
  },
  handleEditAssignments: function() {
    return toastr.error('Editieren ist noch nicht implementiert');
  },
  handleGenerateAssignments: function() {
    return window.location = 'index.php?module=administrator|Schbas|BookAssignments|Generate';
  },
  handleDeleteAssignments: function() {
    toastr.error('Löschen ist noch nicht implementiert');
  },
  render: function() {
    return React.createElement(ButtonGroup, {
      "justified": true
    }, React.createElement(PrepSchoolyear, {
      "schoolyears": this.state.prepSchoolyear,
      "handleSchoolyearChange": this.handleSchoolyearChange
    }), React.createElement(ButtonGroup, null, React.createElement(SchbasClaimStatus, null)), React.createElement(AssignmentController, {
      "prepSchoolyear": this.state.prepSchoolyear.active,
      "handleEdit": this.handleEditAssignments,
      "handleGenerate": this.handleGenerateAssignments,
      "handleDelete": this.handleDeleteAssignments
    }));
  }
});

module.exports = PreparationPanel;
