// Generated by Coffeescript
var DropdownButton, Label, MenuItem, PrepSchoolyear, React;

React = require('react');

React.Bootstrap = require('react-bootstrap');

DropdownButton = React.Bootstrap.DropdownButton;

Label = React.Bootstrap.Label;

MenuItem = React.Bootstrap.MenuItem;

PrepSchoolyear = React.createClass({
  handleSchoolyearChange: function(schoolyearId) {
    return this.props.handleSchoolyearChange(schoolyearId);
  },
  render: function() {
    return React.createElement(DropdownButton, {
      "bsStyle": 'default',
      "title": 'Für Schuljahr ' + this.props.schoolyears.active.name
    }, this.props.schoolyears.alternatives.map(function(schoolyear) {
      var boundSchoolyearChange;
      boundSchoolyearChange = this.handleSchoolyearChange.bind(this, schoolyear.id);
      return React.createElement(MenuItem, {
        "eventKey": schoolyear.id,
        "key": schoolyear.id,
        "onClick": boundSchoolyearChange
      }, schoolyear.name, "\u00a0\u00a0", (schoolyear.entriesExist ? React.createElement(Label, {
        "bsStyle": 'warning'
      }, "Eintr\u00e4ge existieren") : void 0));
    }, this));
  }
});

module.exports = PrepSchoolyear;
