// Generated by Coffeescript
var CheckboxButton, React, SchbasClaimStatus;

React = require('react');

CheckboxButton = require('lib/CheckboxButton.js');

SchbasClaimStatus = React.createClass({
  render: function() {
    return React.createElement(CheckboxButton, {
      "onText": 'Rückmeldeformular aktiv',
      "offText": 'Rückmeldeformular deaktiv',
      "onStyle": 'primary',
      "offStyle": 'warning'
    });
  }
});

module.exports = SchbasClaimStatus;
