// Generated by Coffeescript
var Button, Gradelevel, React;

React = require('react');

React.Bootstrap = require('react-bootstrap');

Button = React.Bootstrap.Button;

Gradelevel = require('./Gradelevel');

module.exports = React.createClass({
  getDefaultProps: function() {
    return {
      handleGradeOfBookAssignmentsDelete: function(book, gradeId, gradeName) {
        return console.log(gradeId);
      },
      handleGradelevelOfBookAssignmentsDelete: function(book, level) {
        return console.log(level);
      },
      handleBookAssignmentsDelete: function(book) {
        return console.log(book);
      }
    };
  },
  handleGradelevelDelete: function(gradelevel) {
    console.log(this.props);
    return this.props.handleGradelevelOfBookAssignmentsDelete(this.props.data, gradelevel);
  },
  handleGradeDelete: function(gradeId, gradeName) {
    return this.props.handleGradeOfBookAssignmentsDelete(this.props.data, gradeId, gradeName);
  },
  handleBookDelete: function() {
    return this.props.handleBookAssignmentsDelete(this.props.data);
  },
  render: function() {
    var gradelevel, rowCount, _i, _len, _ref;
    rowCount = 1;
    _ref = this.props.data.gradelevels;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      gradelevel = _ref[_i];
      rowCount += 1;
    }
    return React.createElement("tbody", null, React.createElement("tr", null, React.createElement("td", {
      "rowSpan": rowCount,
      "className": 'book-column'
    }, React.createElement("b", null, this.props.data.name), React.createElement(Button, {
      "bsStyle": 'danger',
      "className": 'pull-right',
      "onClick": this.handleBookDelete
    }, "Zuweisungen l\u00f6schen"))), this.props.data.gradelevels.map((function(_this) {
      return function(gradelevel) {
        return React.createElement(Gradelevel, {
          "key": gradelevel.level,
          "data": gradelevel,
          "handleGradelevelDelete": _this.handleGradelevelDelete,
          "handleGradeDelete": _this.handleGradeDelete
        });
      };
    })(this)));
  }
});
