// Generated by Coffeescript
var MenuItem, React, SplitButton;

React = require('react');

React.Bootstrap = require('react-bootstrap');

SplitButton = React.Bootstrap.SplitButton;

MenuItem = React.Bootstrap.MenuItem;

module.exports = React.createClass({
  getDefaultProps: function() {
    return {
      handleGradeDelete: function(id, label) {
        return console.log(id);
      }
    };
  },
  handleDelete: function() {
    return this.props.handleGradeDelete(this.props.data.id, this.props.data.label);
  },
  render: function() {
    var title;
    title = [];
    title.push(React.createElement("b", null, this.props.gradelevel, this.props.data.label));
    title.push(React.createElement("i", null, "\u00a0\u00a0(", this.props.data.usersAssigned, ")"));
    return React.createElement("li", null, React.createElement(SplitButton, {
      "bsStyle": 'default',
      "title": title,
      "pullRight": true
    }, React.createElement(MenuItem, {
      "eventKey": 'delete',
      "onClick": this.handleDelete
    }, "Zuweisungen ", React.createElement("br", null), " entfernen")));
  }
});
